import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://taskforce.services">Taskforce Services</a>!
                </h1>

                <p className={styles.description}>
                    Professional Services for Saas Enterprises and Their Customers
                </p>

                <div className={styles.grid}>

                    <a href="settings" className={styles.card}>
                        <h2>Settings &rarr;</h2>
                        <p>Enter your API keys before using services here</p>
                    </a>

                    <a href="invoices" className={styles.card}>
                        <h2>Review Clockify &rarr;</h2>
                        <p>Review monthly hours and create invoices.</p>
                    </a>
                </div>
            </main>

            <footer className={styles.footer}>
                Powered by <a href="taskforce.services">Taskforce Services</a>
            </footer>
        </div>
    );
}
