import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";

export default function Home() {
  return (
    <div className="h-[100vh]">
      <Head>
        <title>Taskforce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-row h-[90vh]">
        <div className="bg-indigo w-80 h-full">
          <p className="font-sans text-white text-xl ">workflow</p>
          <a href="settings">
            <Image
              height={144}
              width={144}
              src="/icons/settings.png"
              alt="Settings"
            />
            <h2 className="text-white font-sans">Settings</h2>
            <p className="text-white font-sans">
              Enter your API keys before using services here
            </p>
          </a>

          <a href="invoices">
            <Image height={144} width={144} src="/icons/bill.jpg" alt="Bill" />
            <h2 className="text-white font-sans">Review Clockify</h2>
            <p className="text-white font-sans">
              Review monthly hours and create invoices.
            </p>
          </a>
        </div>
        <h1>
          Welcome to <a href="https://taskforce.services">Taskforce Services</a>
          !
        </h1>

        <p className={styles.description}>
          Professional Services for Saas Enterprises and Their Customers
        </p>
      </main>

      <footer className={styles.footer}>
        Powered by <a href="taskforce.services">Taskforce Services</a>
      </footer>
    </div>
  );
}
